myfirstproject/gbolahanscrumy/urls.py
from . import views
from django.contrib.auth import urls
from django.urls import path, include
from django.contrib.auth.models import *

from django.views.generic import TemplateView
from django.contrib.auth.forms import UserCreationForm
from .views import *
app_name = 'gbolahanscrumy'
urlpatterns = [

path('', sign_up, name="signup"),
path('accounts/', include('django.contrib.auth.urls'), name = "login"),
path('accounts/', include(urls)),

#path('movegoal/<int:goal_id>', views.move_goal),

path('addgoal', views.add_goal),

path('home/', home, name='home'),

path('accounts/signup/', sign_up, name='signup'),

path('addgoal/', add_goal, name='add'),

path('successpage/', TemplateView.as_view(
        template_name='gbolahanscrumy/successpage.html'), name='successpage'),

path('movegoal/<int:goal_id>', views.move_goal, name="movegoal"),
]

myfirstproject/myfirstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, path
from django.conf.urls import include, url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('gbolahanscrumy/', include('gbolahanscrumy.urls')),    
    path('websocket/', include('websocket.urls')),
]

myfirstproject/websocket/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('test/', views.test, name='test'),
    path('connect', views.connect, name='connect'),
    path('disconnect', views.disconnect, name='disconnect'),
    path('send_message/', views.send_message, name='send message'),
    path('get_recent_messages/', views.get_recent_messages, name='get recent messages'),
]

myfirstproject/gbolahanscrumy/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group, Permission
from django import forms
from django.db import models
from django.core.exceptions import ValidationError
from  gbolahanscrumy.models import ScrumyGoals, GoalStatus
from django.contrib.auth import get_user_model 

User = get_user_model() 
class SignUpForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email    = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Your Emaill'}))
   
    class Meta():
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password1', 'password2']




# ===changin goals===
class DeveloperChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[0:3]])
    class Meta():
        model = GoalStatus
        fields = ['goal_status']


class QAChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[1:4]])

    class Meta():
        model = GoalStatus
        fields = ['goal_status']

class QAChangeGoalForm1(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[2:4]])

    class Meta():
        model = GoalStatus
        fields = ['goal_status']

class OwnerChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[:4]])

    class Meta():
        model = GoalStatus
        fields = ['goal_status']


class AdminChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[:4]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']



#===create goal form ===

class DeveloperCreateGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()    
    goal_status = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in goal_status.order_by('id')[0:1]])
    class Meta():
        model = ScrumyGoals
        fields = ['goal_name', 'created_by', 'moved_by', 'owner', 'user',]

class QACreateGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[0:1]])
    class Meta():
        model = GoalStatus
        fields = ['goal_status']

class QAChangeGoalForm1(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[2:4]])

    class Meta():
        model = GoalStatus
        fields = ['goal_status']


class OwnerCreateGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[0:1]])
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'created_by', 'moved_by', 'owner', 'user', ]

class AdminChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[:4]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']



#===create goal form ===

class DeveloperCreateGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()    
    goal_status = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in goal_status.order_by('id')[0:1]])
    class Meta():
        model = ScrumyGoals
        fields = ['goal_name', 'created_by', 'moved_by', 'owner', 'user',]

class QACreateGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[0:1]])
    class Meta():
        model = ScrumyGoals
        fields = ['goal_name', 'created_by', 'moved_by', 'owner', 'user', ]

class OwnerCreateGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset.order_by('id')[0:1]])
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'created_by', 'moved_by', 'owner', 'user', ]




class ChangeGoalForm(forms.ModelForm):
    queryset = GoalStatus.objects.all()
    goal_status = forms.ChoiceField(choices=[(choice.pk, choice) for choice in queryset[:3]])

    class Meta:
        model = GoalStatus
        fields = ['goal_status']

myfirstproject/gbolahanscrumy/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.db import models
from django.contrib.auth.models import User, Group
from gbolahanscrumy.models import *
from django.http import HttpResponse
from django.conf.urls import url
from django.contrib import admin, messages
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import  get_user_model, login, authenticate
from gbolahanscrumy.forms import (DeveloperCreateGoalForm, QACreateGoalForm, SignUpForm,
                                        QAChangeGoalForm1, ChangeGoalForm, OwnerChangeGoalForm, OwnerCreateGoalForm,
                                        QAChangeGoalForm, AdminChangeGoalForm,DeveloperChangeGoalForm)
import random

def index1(request):
    return HttpResponse("This is a Scrum Application")

User = get_user_model()
# def index(request, *args, **kwargs):    
  #  qs = ScrumyGoals.objects.filter(goal_name="Learn Django").get()
   #  return HttpResponse(f'{qs}')
@login_required(login_url="/gbolahanscrumy/accounts/login")
def home(request):
    current_user = request.user
    users = User.objects.all()
    def get_by_status(status_name):
        goals = GoalStatus.objects.get(status_name=status_name)
        status_goals = goals.scrumygoals_set.all()
        return status_goals

    daily_goals = get_by_status("Daily Goal")
    weekly_goals = get_by_status("Weekly Goal")
    verify_goals = get_by_status("Verify Goal")
    done_goals = get_by_status("Done Goal")

    dictionary = {
        'users': users,
        'weekly_goals': weekly_goals,
        'daily_goals': daily_goals,
        'verify_goals': verify_goals,
        'done_goals': done_goals,
    }
    return render(request, 'gbolahanscrumy/home.html', dictionary)

def move_goal(request, goal_id):
    current_user = request.user
    usr_grp = request.user.groups.all()[0]
    print(usr_grp)
    goals = get_object_or_404(ScrumyGoals, goal_id=goal_id)

    if usr_grp == Group.objects.get(name='Developer') and current_user == goals.user:
    	if request.method == 'POST':
            form = DeveloperChangeGoalForm(request.POST)
            if form.is_valid():
                selected_status = form.save(commit=False)
                selected = GoalStatus.objects.all()
                selected = form.cleaned_data['goal_status']
                choice = GoalStatus.objects.get(id=int(selected))
                goals.goal_status = choice
                goals.save()
                return redirect("/gbolahanscrumy/home")
    		
    	else:
            form = DeveloperChangeGoalForm()
        

    elif usr_grp == Group.objects.get(name='Quality Assurance') and current_user == goals.user:
        if request.method == 'POST':
            form = QAChangeGoalForm(request.POST)
            if form.is_valid():
                selected_status = form.save(commit=False)
                selected = GoalStatus.objects.all()
                selected = form.cleaned_data['goal_status']
                # get_status = selected_status.goal_status
                choice = GoalStatus.objects.get(id=int(selected))
                goals.goal_status = choice
                goals.save()
                return redirect ("/gbolahanscrumy/home")
        else:
            form = QAChangeGoalForm()

    elif usr_grp == Group.objects.get(name='Quality Assurance') and current_user != goals.user:
        print(current_user != goals.user)
        if request.method == 'POST':
            form = QAChangeGoalForm1(request.POST)
            if form.is_valid():
                selected_status = form.save(commit=False)
                selected = GoalStatus.objects.all()
                selected = form.cleaned_data['goal_status']
                choice = GoalStatus.objects.get(id=int(selected))
                goals.goal_status = choice
                goals.save()
                return redirect ("/gbolahanscrumy/home")
        form = QAChangeGoalForm1()

    elif usr_grp == Group.objects.get(name='Owner') and current_user == goals.user:
        if request.method == 'POST':
            form = OwnerChangeGoalForm(request.POST)
            if form.is_valid():
                selected_status = form.save(commit=False)
                selected = form.cleaned_data['goal_status']
                choice = GoalStatus.objects.get(id=int(selected))
                goals.goal_status = choice
                goals.save()
                return redirect ("/gbolahanscrumy/home")
        form = OwnerChangeGoalForm()

    elif usr_grp == Group.objects.get(name='Admin'):
        if request.method == 'POST':
            form = AdminChangeGoalForm(request.POST)
            if form.is_valid():
                selected_status = form.save(commit=False)
                selected = form.cleaned_data['goal_status']
                choice = GoalStatus.objects.get(id=int(selected))
                goals.goal_status = choice
                goals.save()
                return redirect ("/gbolahanscrumy/home")
        
    else:
            
        return HttpResponse('You  are not authorised to move this goal')
    form = AdminChangeGoalForm()
    return render(request, 'gbolahanscrumy/movegoal.html',
                  {'form': form, 'goals': goals, 'current_user': current_user})

  #  obj = ScrumyGoals.objects.get(goal_id=goal_id)
   # form = MoveGoalForm(request.POST or None, instance = obj)
    #if form.is_valid():
     #   obj = form.save(commit= False)
      #  obj.save()
       # return HttpResponseRedirect('/gbolahanscrumy/home' )
    #context = {'move_goal': form }
    #return render(request, 'gbolahanscrumy/movegoal.html', context)

def sign_up(request, *args, **kwargs):
    if request.method =='POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            new_user.groups.add(Group.objects.get(name='Developer'))
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/gbolahanscrumy/successpage')
        else:
            return HttpResponse("Invalid credentials provided: Username or Email already exist")
    else:
        form = SignUpForm()
    return render (request, 'gbolahanscrumy/signup.html', {'form' : form})


def add_goal(request, *args, **kwargs):
    current_user = request.user
    usr_grp = request.user.groups.all()[0]
    dev_grp = Group.objects.get(name='Developer')
    develop = User.objects.filter(groups__name__in=['Developer'])
    qa = User.objects.filter(groups__name__in=['Quality Assurance'])
    admin = User.objects.filter(groups__name__in=['Admin'])
    own = User.objects.filter(groups__name__in=['Owner'])
    if request.user in develop:
        form = DeveloperCreateGoalForm()
        dictionary = {'form' : form}
        if request.method =='POST':
            form = DeveloperCreateGoalForm(request.POST)
            if form.is_valid():
                add_goal = ScrumyGoals()
                add_goal = form.save(commit = False)
                add_goal.goal_id = random.randint(1000, 9999)
                add_goal.goal_status = GoalStatus.objects.get(status_name="Weekly Goal")
                add_goal.save()
                return redirect  ("/gbolahanscrumy/home")       
            return HttpResponse("Invalid credentials provided, please fill out all fields")
        else:
            form = DeveloperCreateGoalForm()
            return render (request, 'gbolahanscrumy/addgoal.html', dictionary)
    


    elif request.user in qa:
        form = QACreateGoalForm(request.POST)
        dictionary = {'form' : form}
        if request.method =='POST':
            form = QACreateGoalForm(request.POST)
            if form.is_valid():
                add_goal = ScrumyGoals()
                add_goal = form.save(commit = False)
                add_goal.goal_id = random.randint(1000, 9999)
                add_goal.goal_status = GoalStatus.objects.get(status_name="Weekly Goal")
                add_goal.save()
                
                return redirect  ("/gbolahanscrumy/home")       
            return HttpResponse("Invalid credentials provided, please fill out all fields")
        else:
            form = QACreateGoalForm()
            return render (request, 'gbolahanscrumy/addgoal.html', dictionary)
    elif request.user in admin:
        form = CreateGoalForm()
        dictionary = {'form' : form}
        if request.method =='POST':
            form = CreateGoalForm(request.POST)
            if form.is_valid():
                add_goal = ScrumyGoals()
                add_goal = form.save(commit = False)
                add_goal.goal_id = random.randint(1000, 9999)
                add_goal.save()
                return redirect  ("/gbolahanscrumy/home")       
            return HttpResponse("Invalid credentials provided, please fill out all fields")
        else:
            form = CreateGoalForm()
    
        return render (request, 'gbolahanscrumy/addgoal.html', dictionary)
    elif request.user in own:
        form = CreateGoalForm()
        dictionary = {'form' : form}
        if request.method =='POST':
            form = CreateGoalForm(request.POST)
            if form.is_valid():
                add_goal = ScrumyGoals()
                add_goal = form.save(commit = False)
                add_goal.goal_id = random.randint(1000, 9999)
                add_goal.save()
                return redirect  ("/gbolahanscrumy/home")       
            return HttpResponse("Invalid credentials provided, please fill out all fields")
        else:
            form = CreateGoalForm()
    

myfirstproject/gbolahanscrumy/templates/gbolahanscrumy/addgoal.html
<!DOCTYPE html>
<html lang="en">

	<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Goal Page</title>
	</head>

<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: sans-serif;
    }

    .container {
        width: 980px;
        height: 400px;
        margin: 50px auto;
        text-align: center;
        background-color: orange;
    }

    body {
        background-color: lightblue;
    }

    form {
        padding-top: 2rem;
    }

    input[type=submit] {
        padding: 10px;
        border: none;
        border-radius: 10px;
        background-color: blue;
        color: #fff;
        cursor: pointer;
    }

    input {
        padding: 10px;
        border-radius: 5px;
    }
</style>

	<body>


<div class="container">
     <p class="p2">User Group: {{ request.user.groups.all }}</p>
        <p>{{ request.user }} is the current authenticated user</p>
    {% if user.is_authenticated  %}
    <form method="POST">

        {{ form.as_p }}

         <input type="submit">
         {% csrf_token %}
     </form>
     {% else %}
<p>You are not allowed to view this page, <a href="{% url 'index' %}">Sign Up Here</a> or <a href="{% url 'login' %}">Login Here</a></p>
     {% endif %}
</div>
</body>

</html>

myfirstproject/gbolahanscrumy/templates/gbolahanscrumy/exception.html
<p> {{error}}
</p>

myfirstproject/gbolahanscrumy/templates/gbolahanscrumy/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home Page</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: sans-serif;
        }

        .container {
            width: 980px;
            height: 400px;
            margin: 50px auto;
            text-align: center;
            background-color: orange;
        }

        body {
            background-color: lightblue;
        }


        table,
        th,
        td {
            border: 1px solid black;
        }

        table {
            width: 100%;
        }

        th {
            height: 50px;
            text-align: center;
        }

        .table-container {
            width: 600px;
            margin: 0 auto;
            padding-top: 50px;
            margin-top: 50px;
        }

        .btn-down {
            margin-top: 20px;

        }
   .btn-down a {
            text-decoration: none;
            background-color: blue;
            padding: 10px;
            border-radius: 20px;
            color: #fff;
        }
    </style>
</head>

<body>

    <div class="container">
        <div class="table-container">
               <p class="p2">User Group: {{ request.user.groups.all }}</p>
        <p>{{ request.user }} is the current authenticated user</p>
            <table>
                <tr>
                    <th>User</th>
                    <th>Weekly Goals</th>
                    <th>Daily Goals</th>
                    <th>Verify Goals</th>
                    <th>Done Goals</th>
                </tr>
                {% for user in users %}
                <tr>
                    <td>{{user}}</td>
                    <td>{% for goal in weekly_goals%}
                        {%if goal.user.username == user.username%}
                        <a href={% url 'gbolahanscrumy:movegoal' goal_id=goal.goal_id %}>{{goal}}</a> || {{goal.goal_id}}

                        {%endif%}
                        {%endfor%}
                    </td>
                    <td>{% for goal in daily_goals%}
                        {%if goal.user.username == user.username%}
                        <a href={% url 'gbolahanscrumy:movegoal' goal_id=goal.goal_id %}>{{goal}}</a> || {{goal.goal_id}}
                        {%endif%}
                        {%endfor%}
                    </td>
                    <td>{% for goal in verify_goals%}
                        {%if goal.user.username == user.username%}
                        <a href={% url 'gbolahanscrumy:movegoal' goal_id=goal.goal_id%}>{{goal}}</a> || {{goal.goal_id}}
                        {%endif%}
                        {%endfor%}
                    </td>
                    <td>{% for goal in done_goals%}
                        {%if goal.user.username == user.username%}
                        <a href={% url 'gbolahanscrumy:movegoal' goal_id=goal.goal_id%}>{{goal}}</a> || {{goal.goal_id}}
                        {%endif%}
                        {%endfor%}
                                        </td>



                    {% endfor %}
                </tr>

            </table>
        </div>

        <p class="btn-down"> <a href={% url 'gbolahanscrumy:add' %}>ADD A GOAL</a></p>
    </div>

</body>

</html>

{%else%} please login or register <p> <a href={% url 'gbolahanscrumy:login' %}>Login to your account</a> or <a href={% url 'gbolahanscrumy:signup' %}>Create a new account by Signing Up</a>{% endif %}



</html>

myfirstproject/gbolahanscrumy/templates/gbolahanscrumy/movegoal.html
<!DOCTYPE html>
<html lang="en">

        <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Move Goal Page</title>
        </head>

<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: sans-serif;
    }

    .container {
        width: 980px;
        height: 400px;
        margin: 50px auto;
        text-align: center;
        background-color: orange;
    }

    body {
        background-color: lightblue;
    }

    form {
        padding-top: 2rem;
    }

    input[type=submit] {
        padding: 10px;
        border: none;
        border-radius: 10px;
        background-color: blue;
        color: #fff;
        cursor: pointer;
    }

    input {
        padding: 10px;
        border-radius: 5px;
    }
     .p2 { background-color: red; }

</style>



        <body>


                <div class="container">

    <form method="POST">
        <h3>Move goal to: {{ form }} </h3>
        <p class="p2">User Group: {{ current_user.groups.all.0 }}</p>
        <p>{{ current_user }} is the current authenticated user</p>
         <p>Current Status: {{ goals.goal_status }}</p>
         <p>{{ goals }} is the goal that want to be moved</p>
         <input type="submit">
         {% csrf_token %}

    </form>
                </div>
        </body>



</html>

myfirstproject/gbolahanscrumy/templates/gbolahanscrumy/successpage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Success Page</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: sans-serif;
        }

        .container {
            width: 980px;
            height: 400px;
            margin: 50px auto;
            text-align: center;
            background-color: orange;
        }

        body {
            background-color: lightblue;
        }

        p {
            margin-top: 20px;
            padding-top: 100px;
            font-size: 30px;
            margin-bottom: 50px;

        }

        .btn-down {
            text-decoration: none;
            background-color: blue;
            padding: 10px;
            border-radius: 20px;
            color: #fff;

        }
    </style>

</head>

<body>
    <div class="container">
        <p>Your Account has been created successfully, <br> Login with your username and password</p>
        <a class="btn-down" href={% url 'gbolahanscrumy:login'%}>Login to your account</a>
    </div>


</body>